name: github pages

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup swarm
        run: |
          mkdir -p ${HOME}/.bee/keystore
          printf ${{ secrets.LIBP2P_KEY_FILE }} > ${HOME}/.bee/keys/libp2p.key
          printf ${{ secrets.SWARM_KEY_FILE }} > ${HOME}/.bee/keys/swarm.key
          wget -q -O - https://raw.githubusercontent.com/ethersphere/bee/master/install.sh | TAG=v0.4.2 bash
          bee --password="x" &
          while ! nc -vz localhost 1633; do sleep 1; done

      # - name: Build for gh-pages
      #   run: |
      #     npm install
      #     npm run-script build
      #     echo "docs.ethswarm.org" > ./build/CNAME
      #     rm ./build/.nojekyll

      # - name: Deploy to gh-pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build

      - name: Build for swarm
        run: |
          rm -rf build
          sed -i "s/baseUrl: '\/'/baseUrl: '\/bzz\/docs\.swarm\.eth\/'/g" docusaurus.config.js
          sed -i s/url: 'https:\/\/docs\.ethswarm\.org'/url: 'https:\/\/gateway\.ethswarm\.org'/g" docusaurus.config.js
          npm run-script build
          rm ./build/.nojekyll

      - name: Swarm upload
        run: |
          tar -cvC build . >build.tar
          REF=$(curl -s --max-time 900 -X POST -H "Content-Type: application/x-tar" -H "Swarm-Index-Document: index.html" -H "Swarm-Error-Document: index.html" --data-binary @./build.tar http://localhost:1633/dirs | jq .reference | tr -d \")
          wget -e robots=off -r -np --page-requisites --no-check-certificate -T10000 -t1  https://gateway.swarm.eth/bzz/$REF
          echo $REF
